### ISSUE TITLE
Why does instantsearch require React?

### ISSUE THREAD

**Issue by millansingh** [algolia/instantsearch.js#2388]
I've installed instantsearch via npm, and it installed fine. However, when I include it in a script and compile the script (with Gulp/Browserify), I get console errors saying that it can't find the 'react' module in various places (like 50 places).

I asked my boss, and he told me to just install react, but I have to wonder why this would use react in the first place, especially when there's a whole separate library specifically for react.

Can someone provide some clarification here on why react is a dependency?

**Comment by Haroenv** [comment]
preact is used internally (with an alias to react), but you should normally not be aware of this as an end-user. Could you share your configuration that causes these error messages so that you're correctly using the production (preact) version? 

Thanks!

**Comment by iam4x** [comment]
This is related to #2279 

Until we come up with a real fix, you can try to use https://github.com/tleunen/babel-plugin-module-resolver and resolve `react` to `preact-compat`

**Comment by millansingh** [comment]
Haroenv, it's a default installation of instantsearch. The site does not use React or Preact for anything.

**Comment by millansingh** [comment]
I can't provide something reproducible, since it's a work project. However, I can tell you that we're building front-end files with Gulp and it's within a Laravel instance, using some of Laravel's Elixir Gulp stuff.

**Comment by iam4x** [comment]
Another workaround would be to use the UMD build in the meantime @millansingh. How do you import InstantSearch.js into your code?

**Comment by millansingh** [comment]
It's imported by a simple require statement, and downloaded as an npm package.

**Comment by hallcyon11** [comment]
this is still happening, i have to install react and react-dom for it to work
```
Error: Cannot find module 'react' from '/Users/asdf/node_modules/instantsearch.js/dist-es5-module/src/widgets/menu-select'
    at /Users/asdf/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/Users/asdf/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/asdf/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/asdf/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/asdf/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/asdf/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
```

**Comment by Haroenv** [comment]
Can you make a repository where this happens @hallcyon11? This should be fixed in v2.2.0

**Comment by hallcyon11** [comment]
"instantsearch.js/dist-es5-module/src/widgets/menu-select/menu-select.js" requires react and react-dom and "instantsearch.js/dist-es5-module/src/components/MenuSelect.js" requires react. I changed them to preact-compat and it compiled...

**Comment by Haroenv** [comment]
Oh, you're right, https://github.com/algolia/instantsearch.js/pull/2460 was merged but not yet released. Can you try `v2.2.1-beta.0`?

**Comment by hallcyon11** [comment]
idk how to do that, i'll just stick with what i have until v2.2.1 is released, thank you for the help.

**Comment by nilsi** [comment]
I tried v2.2.1-beta.0 but it diden't help. I still having some 'react' dependencies like the screenshot shows:

<img width="861" alt="screen shot 2017-10-15 at 15 38 22" src="https://user-images.githubusercontent.com/793881/31585289-a72b9218-b1bf-11e7-8f7b-7460520b0473.png">

**Comment by hallcyon11** [comment]
just do what i did

**Comment by nilsi** [comment]
If I change them manually it compiles but Im getting another problem: 
`Uncaught Error: Cannot find module 'rheostat'`
I can read after doing `npm install`  that:
`npm WARN rheostat@2.1.1 requires a peer of react@>=0.13.x but none was installed.`

Its related to the range slider. Is there any fix for this?

**Comment by iam4x** [comment]
Hello, we have just release v2.2.1 which includes the fix 👍

**Comment by nilsi** [comment]
Still having this issue from here:
https://github.com/algolia/instantsearch.js/blob/e608a7a147d237722570d7696011ba269b73679a/src/components/MenuSelect.js

https://github.com/algolia/instantsearch.js/blob/e608a7a147d237722570d7696011ba269b73679a/src/components/MenuSelect.js

And multiple places in rheostat for example here:
https://github.com/algolia/rheostat/blob/dist-preact/src/Slider.jsx

**Comment by Haroenv** [comment]
Weird! I thought https://github.com/algolia/instantsearch.js/pull/2460 fixed that first problem, was it reverted @iam4x ?

**Comment by Haroenv** [comment]
I think that this is fixed now. Please open a new issue if you have issues regarding wrong aliasing of React
