### ISSUE TITLE
hits: transformData is called on main response when no results

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#667]
Not sure if this is a bug or a _feature_, but it is in any case suprising.

If I define a `transformData` method to the `hits` widget, it is correctly called with each hit from the response. But if I do a query that has no results, it is also called, with `data` being equal to the whole API response (including `nbHits`, `hitsPerPage`, `hits`, etc).

This force me to add a check at the start of my `transformData` to check for `(data.hits && data.hits.length === 0)` (for example) to know that I'm in a "no results" call.

This feels quite hacky, and I think we should provide a better way of handling it. Maybe something like this:

```javascript
// pseudo-code...

// transformData only called on each hit, not on the "no result" part
hits({
  transformData: function() {}
});

// Passing it as an object lets us define a method for each case
hits({
  transformData: {
    results: function() {},
    noResults: function() {}
}
```

WDYT?

**Comment by vvo** [comment]
Yes we may have introduced a "bad" API here. But this is already out and since we did not do any beta-release channel we are kind of stuck, we would have to bump major. (That's another discussion we will have).

What we could do thought is hide the global transformData in our documentation and force people to use the object one everytime. Because exhaustivity in the API here is important as you discovered.

So I would go for hiding the global option instead of introducing another behavior that would require a breaking change.

**Comment by pixelastic** [comment]
Actually... we already implemented it, and it's already documented...

`transformData` already accepts an object with keys equals to the one used in `template`. In that case, only the matching function is called. If a method is passed directly, it will be called for every template.

**Comment by vvo** [comment]
indeed and we already don't document the global function even if it works. Since we are not documenting it, we could also just error if a global function is passed as the usage. Because it's not the usage we are expecting.

One of the 1.1 could be precise usage checks and reporting

**Comment by pixelastic** [comment]
Well, all other widgets expect a global function and not an object.

In the end I think this whole part of the code will need some refactoring because it buried quite deep down into the Template code, while still forcing us to pass a bound object from the top widget.

**Comment by vvo** [comment]
I still don't remember why this couldnt be handled just by passing a template function :D

**Comment by bobylito** [comment]
The main reason is that we may have different template for which we want to be able to identify the kind of state where into. In our current implementation this is the hits widgets, and when we have an result template the context of the template is bound to a single hit, whereas we bind the whole result object when we don't have any result. So the signature is different for the object itself. One solution is to pass the template key to the transformData function, but it makes the user have to handle the different signature using another parameter: 

```js 
transformData: (val, type) => {
  if(type==='result;) //blah
  else(type==='no-result') //blouh
}
```

In the implementation we've chosen, the user provides two kind of transformData which removes this ugly boilerplate.
